export const CUSTOM_PRE_ORDER_ADD_REQUEST = 'CUSTOM_PRE_ORDER_ADD_REQUEST'
export const CUSTOM_PRE_ORDER_ADD_SUCCESS = 'CUSTOM_PRE_ORDER_ADD_SUCCESS'
export const CUSTOM_PRE_ORDER_ADD_FAIL = 'CUSTOM_PRE_ORDER_ADD_FAIL'
export const CUSTOM_PRE_ORDER_ADD_RESET = 'CUSTOM_PRE_ORDER_ADD_RESET'

export const CUSTOM_PRE_ORDER_LIST_REQUEST = 'CUSTOM_PRE_ORDER_LIST_REQUEST'
export const CUSTOM_PRE_ORDER_LIST_SUCCESS = 'CUSTOM_PRE_ORDER_LIST_SUCCESS'
export const CUSTOM_PRE_ORDER_LIST_FAIL = 'CUSTOM_PRE_ORDER_LIST_FAIL'

export const CUSTOM_PRE_ORDER_DETAILS_REQUEST =
  'CUSTOM_PRE_ORDER_DETAILS_REQUEST'
export const CUSTOM_PRE_ORDER_DETAILS_SUCCESS =
  'CUSTOM_PRE_ORDER_DETAILS_SUCCESS'
export const CUSTOM_PRE_ORDER_DETAILS_FAIL = 'CUSTOM_PRE_ORDER_DETAILS_FAIL'

export const CUSTOM_PRE_ORDER_UPDATE_REQUEST = 'CUSTOM_PRE_ORDER_UPDATE_REQUEST'
export const CUSTOM_PRE_ORDER_UPDATE_SUCCESS = 'CUSTOM_PRE_ORDER_UPDATE_SUCCESS'
export const CUSTOM_PRE_ORDER_UPDATE_FAIL = 'CUSTOM_PRE_ORDER_UPDATE_FAIL'
export const CUSTOM_PRE_ORDER_UPDATE_RESET = 'CUSTOM_PRE_ORDER_UPDATE_RESET'

export const CUSTOM_PRE_ORDER_DELETE_REQUEST = 'CUSTOM_PRE_ORDER_DELETE_REQUEST'
export const CUSTOM_PRE_ORDER_DELETE_SUCCESS = 'CUSTOM_PRE_ORDER_DELETE_SUCCESS'
export const CUSTOM_PRE_ORDER_DELETE_FAIL = 'CUSTOM_PRE_ORDER_DELETE_FAIL'
