export const CUSTOM_STAIN_REQUEST = 'CUSTOM_STAIN_REQUEST'
export const CUSTOM_STAIN_SUCCESS = 'CUSTOM_STAIN_SUCCESS'
export const CUSTOM_STAIN_FAIL = 'CUSTOM_STAIN_FAIL'

export const CUSTOM_STAIN_DETAILS_REQUEST = 'CUSTOM_STAIN_DETAILS_REQUEST'
export const CUSTOM_STAIN_DETAILS_SUCCESS = 'CUSTOM_STAIN_DETAILS_SUCCESS'
export const CUSTOM_STAIN_DETAILS_FAIL = 'CUSTOM_STAIN_DETAILS_FAIL'

export const CUSTOM_STAIN_CREATE_REQUEST = 'CUSTOM_STAIN_CREATE_REQUEST'
export const CUSTOM_STAIN_CREATE_SUCCESS = 'CUSTOM_STAIN_CREATE_SUCCESS'
export const CUSTOM_STAIN_CREATE_FAIL = 'CUSTOM_STAIN_CREATE_FAIL'
export const CUSTOM_STAIN_CREATE_RESET = 'CUSTOM_STAIN_CREATE_RESET'

export const CUSTOM_STAIN_UPDATE_REQUEST = 'CUSTOM_STAIN_UPDATE_REQUEST'
export const CUSTOM_STAIN_UPDATE_SUCCESS = 'CUSTOM_STAIN_UPDATE_SUCCESS'
export const CUSTOM_STAIN_UPDATE_FAIL = 'CUSTOM_STAIN_UPDATE_FAIL'
export const CUSTOM_STAIN_UPDATE_RESET = 'CUSTOM_STAIN_UPDATE_RESET'

export const CUSTOM_STAIN_DELETE_REQUEST = 'CUSTOM_STAIN_DELETE_REQUEST'
export const CUSTOM_STAIN_DELETE_SUCCESS = 'CUSTOM_STAIN_DELETE_SUCCESS'
export const CUSTOM_STAIN_DELETE_FAIL = 'CUSTOM_STAIN_DELETE_FAIL'
