export const CUSTOM_PAINT_REQUEST = 'CUSTOM_PAINT_REQUEST'
export const CUSTOM_PAINT_SUCCESS = 'CUSTOM_PAINT_SUCCESS'
export const CUSTOM_PAINT_FAIL = 'CUSTOM_PAINT_FAIL'

export const CUSTOM_PAINT_DETAILS_REQUEST = 'CUSTOM_PAINT_DETAILS_REQUEST'
export const CUSTOM_PAINT_DETAILS_SUCCESS = 'CUSTOM_PAINT_DETAILS_SUCCESS'
export const CUSTOM_PAINT_DETAILS_FAIL = 'CUSTOM_PAINT_DETAILS_FAIL'

export const CUSTOM_PAINT_CREATE_REQUEST = 'CUSTOM_PAINT_CREATE_REQUEST'
export const CUSTOM_PAINT_CREATE_SUCCESS = 'CUSTOM_PAINT_CREATE_SUCCESS'
export const CUSTOM_PAINT_CREATE_FAIL = 'CUSTOM_PAINT_CREATE_FAIL'
export const CUSTOM_PAINT_CREATE_RESET = 'CUSTOM_PAINT_CREATE_RESET'

export const CUSTOM_PAINT_UPDATE_REQUEST = 'CUSTOM_PAINT_UPDATE_REQUEST'
export const CUSTOM_PAINT_UPDATE_SUCCESS = 'CUSTOM_PAINT_UPDATE_SUCCESS'
export const CUSTOM_PAINT_UPDATE_FAIL = 'CUSTOM_PAINT_UPDATE_FAIL'
export const CUSTOM_PAINT_UPDATE_RESET = 'CUSTOM_PAINT_UPDATE_RESET'

export const CUSTOM_PAINT_DELETE_REQUEST = 'CUSTOM_PAINT_DELETE_REQUEST'
export const CUSTOM_PAINT_DELETE_SUCCESS = 'CUSTOM_PAINT_DELETE_SUCCESS'
export const CUSTOM_PAINT_DELETE_FAIL = 'CUSTOM_PAINT_DELETE_FAIL'
