export const CUSTOM_BASE_REQUEST = 'CUSTOM_BASE_REQUEST'
export const CUSTOM_BASE_SUCCESS = 'CUSTOM_BASE_SUCCESS'
export const CUSTOM_BASE_FAIL = 'CUSTOM_BASE_FAIL'

export const CUSTOM_BASE_DETAILS_REQUEST = 'CUSTOM_BASE_DETAILS_REQUEST'
export const CUSTOM_BASE_DETAILS_SUCCESS = 'CUSTOM_BASE_DETAILS_SUCCESS'
export const CUSTOM_BASE_DETAILS_FAIL = 'CUSTOM_BASE_DETAILS_FAIL'

export const CUSTOM_BASE_CREATE_REQUEST = 'CUSTOM_BASE_CREATE_REQUEST'
export const CUSTOM_BASE_CREATE_SUCCESS = 'CUSTOM_BASE_CREATE_SUCCESS'
export const CUSTOM_BASE_CREATE_FAIL = 'CUSTOM_BASE_CREATE_FAIL'
export const CUSTOM_BASE_CREATE_RESET = 'CUSTOM_BASE_CREATE_RESET'

export const CUSTOM_BASE_UPDATE_REQUEST = 'CUSTOM_BASE_UPDATE_REQUEST'
export const CUSTOM_BASE_UPDATE_SUCCESS = 'CUSTOM_BASE_UPDATE_SUCCESS'
export const CUSTOM_BASE_UPDATE_FAIL = 'CUSTOM_BASE_UPDATE_FAIL'
export const CUSTOM_BASE_UPDATE_RESET = 'CUSTOM_BASE_UPDATE_RESET'

export const CUSTOM_BASE_DELETE_REQUEST = 'CUSTOM_BASE_DELETE_REQUEST'
export const CUSTOM_BASE_DELETE_SUCCESS = 'CUSTOM_BASE_DELETE_SUCCESS'
export const CUSTOM_BASE_DELETE_FAIL = 'CUSTOM_BASE_DELETE_FAIL'
