export const CUSTOM_PRODUCT_REQUEST = 'CUSTOM_PRODUCT_REQUEST'
export const CUSTOM_PRODUCT_SUCCESS = 'CUSTOM_PRODUCT_SUCCESS'
export const CUSTOM_PRODUCT_FAIL = 'CUSTOM_PRODUCT_FAIL'

export const CUSTOM_PRODUCT_DETAILS_REQUEST = 'CUSTOM_PRODUCT_DETAILS_REQUEST'
export const CUSTOM_PRODUCT_DETAILS_SUCCESS = 'CUSTOM_PRODUCT_DETAILS_SUCCESS'
export const CUSTOM_PRODUCT_DETAILS_FAIL = 'CUSTOM_PRODUCT_DETAILS_FAIL'

export const CUSTOM_PRODUCT_CREATE_REQUEST = 'CUSTOM_PRODUCT_CREATE_REQUEST'
export const CUSTOM_PRODUCT_CREATE_SUCCESS = 'CUSTOM_PRODUCT_CREATE_SUCCESS'
export const CUSTOM_PRODUCT_CREATE_FAIL = 'CUSTOM_PRODUCT_CREATE_FAIL'
export const CUSTOM_PRODUCT_CREATE_RESET = 'CUSTOM_PRODUCT_CREATE_RESET'

export const CUSTOM_PRODUCT_UPDATE_REQUEST = 'CUSTOM_PRODUCT_UPDATE_REQUEST'
export const CUSTOM_PRODUCT_UPDATE_SUCCESS = 'CUSTOM_PRODUCT_UPDATE_SUCCESS'
export const CUSTOM_PRODUCT_UPDATE_FAIL = 'CUSTOM_PRODUCT_UPDATE_FAIL'
export const CUSTOM_PRODUCT_UPDATE_RESET = 'CUSTOM_PRODUCT_UPDATE_RESET'

export const CUSTOM_PRODUCT_DELETE_REQUEST = 'CUSTOM_PRODUCT_DELETE_REQUEST'
export const CUSTOM_PRODUCT_DELETE_SUCCESS = 'CUSTOM_PRODUCT_DELETE_SUCCESS'
export const CUSTOM_PRODUCT_DELETE_FAIL = 'CUSTOM_PRODUCT_DELETE_FAIL'
