export const CUSTOM_ACCENT_REQUEST = 'CUSTOM_ACCENT_REQUEST'
export const CUSTOM_ACCENT_SUCCESS = 'CUSTOM_ACCENT_SUCCESS'
export const CUSTOM_ACCENT_FAIL = 'CUSTOM_ACCENT_FAIL'

export const CUSTOM_ACCENT_DETAILS_REQUEST = 'CUSTOM_ACCENT_DETAILS_REQUEST'
export const CUSTOM_ACCENT_DETAILS_SUCCESS = 'CUSTOM_ACCENT_DETAILS_SUCCESS'
export const CUSTOM_ACCENT_DETAILS_FAIL = 'CUSTOM_ACCENT_DETAILS_FAIL'

export const CUSTOM_ACCENT_CREATE_REQUEST = 'CUSTOM_ACCENT_CREATE_REQUEST'
export const CUSTOM_ACCENT_CREATE_SUCCESS = 'CUSTOM_ACCENT_CREATE_SUCCESS'
export const CUSTOM_ACCENT_CREATE_FAIL = 'CUSTOM_ACCENT_CREATE_FAIL'
export const CUSTOM_ACCENT_CREATE_RESET = 'CUSTOM_ACCENT_CREATE_RESET'

export const CUSTOM_ACCENT_UPDATE_REQUEST = 'CUSTOM_ACCENT_UPDATE_REQUEST'
export const CUSTOM_ACCENT_UPDATE_SUCCESS = 'CUSTOM_ACCENT_UPDATE_SUCCESS'
export const CUSTOM_ACCENT_UPDATE_FAIL = 'CUSTOM_ACCENT_UPDATE_FAIL'
export const CUSTOM_ACCENT_UPDATE_RESET = 'CUSTOM_ACCENT_UPDATE_RESET'

export const CUSTOM_ACCENT_DELETE_REQUEST = 'CUSTOM_ACCENT_DELETE_REQUEST'
export const CUSTOM_ACCENT_DELETE_SUCCESS = 'CUSTOM_ACCENT_DELETE_SUCCESS'
export const CUSTOM_ACCENT_DELETE_FAIL = 'CUSTOM_ACCENT_DELETE_FAIL'
