export const CUSTOM_SPECIES_REQUEST = 'CUSTOM_SPECIES_REQUEST'
export const CUSTOM_SPECIES_SUCCESS = 'CUSTOM_SPECIES_SUCCESS'
export const CUSTOM_SPECIES_FAIL = 'CUSTOM_SPECIES_FAIL'

export const CUSTOM_SPECIES_DETAILS_REQUEST = 'CUSTOM_SPECIES_DETAILS_REQUEST'
export const CUSTOM_SPECIES_DETAILS_SUCCESS = 'CUSTOM_SPECIES_DETAILS_SUCCESS'
export const CUSTOM_SPECIES_DETAILS_FAIL = 'CUSTOM_SPECIES_DETAILS_FAIL'

export const CUSTOM_SPECIES_CREATE_REQUEST = 'CUSTOM_SPECIES_CREATE_REQUEST'
export const CUSTOM_SPECIES_CREATE_SUCCESS = 'CUSTOM_SPECIES_CREATE_SUCCESS'
export const CUSTOM_SPECIES_CREATE_FAIL = 'CUSTOM_SPECIES_CREATE_FAIL'
export const CUSTOM_SPECIES_CREATE_RESET = 'CUSTOM_SPECIES_CREATE_RESET'

export const CUSTOM_SPECIES_UPDATE_REQUEST = 'CUSTOM_SPECIES_UPDATE_REQUEST'
export const CUSTOM_SPECIES_UPDATE_SUCCESS = 'CUSTOM_SPECIES_UPDATE_SUCCESS'
export const CUSTOM_SPECIES_UPDATE_FAIL = 'CUSTOM_SPECIES_UPDATE_FAIL'
export const CUSTOM_SPECIES_UPDATE_RESET = 'CUSTOM_SPECIES_UPDATE_RESET'

export const CUSTOM_SPECIES_DELETE_REQUEST = 'CUSTOM_SPECIES_DELETE_REQUEST'
export const CUSTOM_SPECIES_DELETE_SUCCESS = 'CUSTOM_SPECIES_DELETE_SUCCESS'
export const CUSTOM_SPECIES_DELETE_FAIL = 'CUSTOM_SPECIES_DELETE_FAIL'
