export const GALLERY_PHOTO_LIST_REQUEST = 'GALLERY_PHOTO_LIST_REQUEST'
export const GALLERY_PHOTO_LIST_SUCCESS = 'GALLERY_PHOTO_LIST_SUCCESS'
export const GALLERY_PHOTO_LIST_FAIL = 'GALLERY_PHOTO_LIST_FAIL'

export const GALLERY_PHOTO_DETAILS_REQUEST = 'GALLERY_PHOTO_DETAILS_REQUEST'
export const GALLERY_PHOTO_DETAILS_SUCCESS = 'GALLERY_PHOTO_DETAILS_SUCCESS'
export const GALLERY_PHOTO_DETAILS_FAIL = 'GALLERY_PHOTO_DETAILS_FAIL'

export const GALLERY_PHOTO_CREATE_REQUEST = 'GALLERY_PHOTO_CREATE_REQUEST'
export const GALLERY_PHOTO_CREATE_SUCCESS = 'GALLERY_PHOTO_CREATE_SUCCESS'
export const GALLERY_PHOTO_CREATE_FAIL = 'GALLERY_PHOTO_CREATE_FAIL'
export const GALLERY_PHOTO_CREATE_RESET = 'GALLERY_PHOTO_CREATE_RESET'

export const GALLERY_PHOTO_UPDATE_REQUEST = 'GALLERY_PHOTO_UPDATE_REQUEST'
export const GALLERY_PHOTO_UPDATE_SUCCESS = 'GALLERY_PHOTO_UPDATE_SUCCESS'
export const GALLERY_PHOTO_UPDATE_FAIL = 'GALLERY_PHOTO_UPDATE_FAIL'
export const GALLERY_PHOTO_UPDATE_RESET = 'GALLERY_PHOTO_UPDATE_RESET'

export const GALLERY_PHOTO_DELETE_REQUEST = 'GALLERY_PHOTO_DELETE_REQUEST'
export const GALLERY_PHOTO_DELETE_SUCCESS = 'GALLERY_PHOTO_DELETE_SUCCESS'
export const GALLERY_PHOTO_DELETE_FAIL = 'GALLERY_PHOTO_DELETE_FAIL'
