export const BEDFRAME_PRICE_REQUEST = 'BEDFRAME_PRICE_REQUEST'
export const BEDFRAME_PRICE_SUCCESS = 'BEDFRAME_PRICE_SUCCESS'
export const BEDFRAME_PRICE_FAIL = 'BEDFRAME_PRICE_FAIL'

export const BEDFRAME_PRICE_DETAILS_REQUEST = 'BEDFRAME_PRICE_DETAILS_REQUEST'
export const BEDFRAME_PRICE_DETAILS_SUCCESS = 'BEDFRAME_PRICE_DETAILS_SUCCESS'
export const BEDFRAME_PRICE_DETAILS_FAIL = 'BEDFRAME_PRICE_DETAILS_FAIL'

export const BEDFRAME_PRICE_CREATE_REQUEST = 'BEDFRAME_PRICE_CREATE_REQUEST'
export const BEDFRAME_PRICE_CREATE_SUCCESS = 'BEDFRAME_PRICE_CREATE_SUCCESS'
export const BEDFRAME_PRICE_CREATE_FAIL = 'BEDFRAME_PRICE_CREATE_FAIL'
export const BEDFRAME_PRICE_CREATE_RESET = 'BEDFRAME_PRICE_CREATE_RESET'

export const BEDFRAME_PRICE_UPDATE_REQUEST = 'BEDFRAME_PRICE_UPDATE_REQUEST'
export const BEDFRAME_PRICE_UPDATE_SUCCESS = 'BEDFRAME_PRICE_UPDATE_SUCCESS'
export const BEDFRAME_PRICE_UPDATE_FAIL = 'BEDFRAME_PRICE_UPDATE_FAIL'
export const BEDFRAME_PRICE_UPDATE_RESET = 'BEDFRAME_PRICE_UPDATE_RESET'

export const BEDFRAME_PRICE_DELETE_REQUEST = 'BEDFRAME_PRICE_DELETE_REQUEST'
export const BEDFRAME_PRICE_DELETE_SUCCESS = 'BEDFRAME_PRICE_DELETE_SUCCESS'
export const BEDFRAME_PRICE_DELETE_FAIL = 'BEDFRAME_PRICE_DELETE_FAIL'
