export const ACCENT_REQUEST = 'ACCENT_REQUEST'
export const ACCENT_SUCCESS = 'ACCENT_SUCCESS'
export const ACCENT_FAIL = 'ACCENT_FAIL'

export const ACCENT_DETAILS_REQUEST = 'ACCENT_DETAILS_REQUEST'
export const ACCENT_DETAILS_SUCCESS = 'ACCENT_DETAILS_SUCCESS'
export const ACCENT_DETAILS_FAIL = 'ACCENT_DETAILS_FAIL'

export const ACCENT_CREATE_REQUEST = 'ACCENT_CREATE_REQUEST'
export const ACCENT_CREATE_SUCCESS = 'ACCENT_CREATE_SUCCESS'
export const ACCENT_CREATE_FAIL = 'ACCENT_CREATE_FAIL'
export const ACCENT_CREATE_RESET = 'ACCENT_CREATE_RESET'

export const ACCENT_UPDATE_REQUEST = 'ACCENT_UPDATE_REQUEST'
export const ACCENT_UPDATE_SUCCESS = 'ACCENT_UPDATE_SUCCESS'
export const ACCENT_UPDATE_FAIL = 'ACCENT_UPDATE_FAIL'
export const ACCENT_UPDATE_RESET = 'ACCENT_UPDATE_RESET'

export const ACCENT_DELETE_REQUEST = 'ACCENT_DELETE_REQUEST'
export const ACCENT_DELETE_SUCCESS = 'ACCENT_DELETE_SUCCESS'
export const ACCENT_DELETE_FAIL = 'ACCENT_DELETE_FAIL'
