export const BASE_REQUEST = 'BASE_REQUEST'
export const BASE_SUCCESS = 'BASE_SUCCESS'
export const BASE_FAIL = 'BASE_FAIL'

export const BASE_DETAILS_REQUEST = 'BASE_DETAILS_REQUEST'
export const BASE_DETAILS_SUCCESS = 'BASE_DETAILS_SUCCESS'
export const BASE_DETAILS_FAIL = 'BASE_DETAILS_FAIL'

export const BASE_CREATE_REQUEST = 'BASE_CREATE_REQUEST'
export const BASE_CREATE_SUCCESS = 'BASE_CREATE_SUCCESS'
export const BASE_CREATE_FAIL = 'BASE_CREATE_FAIL'
export const BASE_CREATE_RESET = 'BASE_CREATE_RESET'

export const BASE_UPDATE_REQUEST = 'BASE_UPDATE_REQUEST'
export const BASE_UPDATE_SUCCESS = 'BASE_UPDATE_SUCCESS'
export const BASE_UPDATE_FAIL = 'BASE_UPDATE_FAIL'
export const BASE_UPDATE_RESET = 'BASE_UPDATE_RESET'

export const BASE_DELETE_REQUEST = 'BASE_DELETE_REQUEST'
export const BASE_DELETE_SUCCESS = 'BASE_DELETE_SUCCESS'
export const BASE_DELETE_FAIL = 'BASE_DELETE_FAIL'
