export const BEDFRAME_REQUEST = 'BEDFRAME_REQUEST'
export const BEDFRAME_SUCCESS = 'BEDFRAME_SUCCESS'
export const BEDFRAME_FAIL = 'BEDFRAME_FAIL'

export const BEDFRAME_DETAILS_REQUEST = 'BEDFRAME_DETAILS_REQUEST'
export const BEDFRAME_DETAILS_SUCCESS = 'BEDFRAME_DETAILS_SUCCESS'
export const BEDFRAME_DETAILS_FAIL = 'BEDFRAME_DETAILS_FAIL'

export const BEDFRAME_CREATE_REQUEST = 'BEDFRAME_CREATE_REQUEST'
export const BEDFRAME_CREATE_SUCCESS = 'BEDFRAME_CREATE_SUCCESS'
export const BEDFRAME_CREATE_FAIL = 'BEDFRAME_CREATE_FAIL'
export const BEDFRAME_CREATE_RESET = 'BEDFRAME_CREATE_RESET'

export const BEDFRAME_UPDATE_REQUEST = 'BEDFRAME_UPDATE_REQUEST'
export const BEDFRAME_UPDATE_SUCCESS = 'BEDFRAME_UPDATE_SUCCESS'
export const BEDFRAME_UPDATE_FAIL = 'BEDFRAME_UPDATE_FAIL'
export const BEDFRAME_UPDATE_RESET = 'BEDFRAME_UPDATE_RESET'

export const BEDFRAME_DELETE_REQUEST = 'BEDFRAME_DELETE_REQUEST'
export const BEDFRAME_DELETE_SUCCESS = 'BEDFRAME_DELETE_SUCCESS'
export const BEDFRAME_DELETE_FAIL = 'BEDFRAME_DELETE_FAIL'
