export const DOOR_REQUEST = 'DOOR_REQUEST'
export const DOOR_SUCCESS = 'DOOR_SUCCESS'
export const DOOR_FAIL = 'DOOR_FAIL'

export const DOOR_DETAILS_REQUEST = 'DOOR_DETAILS_REQUEST'
export const DOOR_DETAILS_SUCCESS = 'DOOR_DETAILS_SUCCESS'
export const DOOR_DETAILS_FAIL = 'DOOR_DETAILS_FAIL'

export const DOOR_CREATE_REQUEST = 'DOOR_CREATE_REQUEST'
export const DOOR_CREATE_SUCCESS = 'DOOR_CREATE_SUCCESS'
export const DOOR_CREATE_FAIL = 'DOOR_CREATE_FAIL'
export const DOOR_CREATE_RESET = 'DOOR_CREATE_RESET'

export const DOOR_UPDATE_REQUEST = 'DOOR_UPDATE_REQUEST'
export const DOOR_UPDATE_SUCCESS = 'DOOR_UPDATE_SUCCESS'
export const DOOR_UPDATE_FAIL = 'DOOR_UPDATE_FAIL'
export const DOOR_UPDATE_RESET = 'DOOR_UPDATE_RESET'

export const DOOR_DELETE_REQUEST = 'DOOR_DELETE_REQUEST'
export const DOOR_DELETE_SUCCESS = 'DOOR_DELETE_SUCCESS'
export const DOOR_DELETE_FAIL = 'DOOR_DELETE_FAIL'
