export const EST_COMP_LIST_REQUEST = 'EST_COMP_LIST_REQUEST'
export const EST_COMP_LIST_SUCCESS = 'EST_COMP_LIST_SUCCESS'
export const EST_COMP_LIST_FAIL = 'EST_COMP_LIST_FAIL'

export const EST_COMP_DETAILS_REQUEST = 'EST_COMP_DETAILS_REQUEST'
export const EST_COMP_DETAILS_SUCCESS = 'EST_COMP_DETAILS_SUCCESS'
export const EST_COMP_DETAILS_FAIL = 'EST_COMP_DETAILS_FAIL'

export const EST_COMP_CREATE_REQUEST = 'EST_COMP_CREATE_REQUEST'
export const EST_COMP_CREATE_SUCCESS = 'EST_COMP_CREATE_SUCCESS'
export const EST_COMP_CREATE_FAIL = 'EST_COMP_CREATE_FAIL'
export const EST_COMP_CREATE_RESET = 'EST_COMP_CREATE_RESET'

export const EST_COMP_UPDATE_REQUEST = 'EST_COMP_UPDATE_REQUEST'
export const EST_COMP_UPDATE_SUCCESS = 'EST_COMP_UPDATE_SUCCESS'
export const EST_COMP_UPDATE_FAIL = 'EST_COMP_UPDATE_FAIL'
export const EST_COMP_UPDATE_RESET = 'EST_COMP_UPDATE_RESET'

export const EST_COMP_DELETE_REQUEST = 'EST_COMP_DELETE_REQUEST'
export const EST_COMP_DELETE_SUCCESS = 'EST_COMP_DELETE_SUCCESS'
export const EST_COMP_DELETE_FAIL = 'EST_COMP_DELETE_FAIL'
