export const PAINT_REQUEST = 'PAINT_REQUEST'
export const PAINT_SUCCESS = 'PAINT_SUCCESS'
export const PAINT_FAIL = 'PAINT_FAIL'

export const PAINT_DETAILS_REQUEST = 'PAINT_DETAILS_REQUEST'
export const PAINT_DETAILS_SUCCESS = 'PAINT_DETAILS_SUCCESS'
export const PAINT_DETAILS_FAIL = 'PAINT_DETAILS_FAIL'

export const PAINT_CREATE_REQUEST = 'PAINT_CREATE_REQUEST'
export const PAINT_CREATE_SUCCESS = 'PAINT_CREATE_SUCCESS'
export const PAINT_CREATE_FAIL = 'PAINT_CREATE_FAIL'
export const PAINT_CREATE_RESET = 'PAINT_CREATE_RESET'

export const PAINT_UPDATE_REQUEST = 'PAINT_UPDATE_REQUEST'
export const PAINT_UPDATE_SUCCESS = 'PAINT_UPDATE_SUCCESS'
export const PAINT_UPDATE_FAIL = 'PAINT_UPDATE_FAIL'
export const PAINT_UPDATE_RESET = 'PAINT_UPDATE_RESET'

export const PAINT_DELETE_REQUEST = 'PAINT_DELETE_REQUEST'
export const PAINT_DELETE_SUCCESS = 'PAINT_DELETE_SUCCESS'
export const PAINT_DELETE_FAIL = 'PAINT_DELETE_FAIL'
