export const STAIN_REQUEST = 'STAIN_REQUEST'
export const STAIN_SUCCESS = 'STAIN_SUCCESS'
export const STAIN_FAIL = 'STAIN_FAIL'

export const STAIN_DETAILS_REQUEST = 'STAIN_DETAILS_REQUEST'
export const STAIN_DETAILS_SUCCESS = 'STAIN_DETAILS_SUCCESS'
export const STAIN_DETAILS_FAIL = 'STAIN_DETAILS_FAIL'

export const STAIN_CREATE_REQUEST = 'STAIN_CREATE_REQUEST'
export const STAIN_CREATE_SUCCESS = 'STAIN_CREATE_SUCCESS'
export const STAIN_CREATE_FAIL = 'STAIN_CREATE_FAIL'
export const STAIN_CREATE_RESET = 'STAIN_CREATE_RESET'

export const STAIN_UPDATE_REQUEST = 'STAIN_UPDATE_REQUEST'
export const STAIN_UPDATE_SUCCESS = 'STAIN_UPDATE_SUCCESS'
export const STAIN_UPDATE_FAIL = 'STAIN_UPDATE_FAIL'
export const STAIN_UPDATE_RESET = 'STAIN_UPDATE_RESET'

export const STAIN_DELETE_REQUEST = 'STAIN_DELETE_REQUEST'
export const STAIN_DELETE_SUCCESS = 'STAIN_DELETE_SUCCESS'
export const STAIN_DELETE_FAIL = 'STAIN_DELETE_FAIL'
